### Create user
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "name": "Mathieu"
}

### Get user info
GET http://localhost:8080/v1/users
Authorization: ApiKey 6d4e79dc8f8ca85f86256f95732d37f0629b1c654a86934fc3e760cc5f472da2
